---
- name: Collect log files from controlNode
  hosts: ControlNode
  tasks:
    - name: Collecting Log Files from controlNode
      fetch:
        src: /var/log/syslog
        dest: /home/ken/CPE243_HOA7/logfiles.json
        flat: yes
      register: syslog_result
